import test from 'node:test';
import assert from 'node:assert/strict';
import {uiHarness} from './ui-harness.mjs';
import {mountBattleUI} from '../web/battle-ui.js';
import {battleFixture} from './battle-fixtures.js';
import {normalize} from '../web/state.js';
test('manual battle waits indefinitely per event, hides the player, updates both bars and settles once',()=>{const h=uiHarness(),f=battleFixture();let commits=0,ui;const chat={controls(){},isPending(){return false;},apply(){commits++;}};try{ui=mountBattleUI(f.state,{render:()=>ui.render(),persist(){},chat,assetBase:'/'});ui.start(f.scene);h.clock(1);h.clock(1501);assert.equal(f.state.battlePlayback.index,0);assert.equal(h.get('battle-next').disabled,false);assert.equal(h.get('battle-left').hidden,true);h.clock(60001);assert.equal(f.state.battlePlayback.index,0);const bars=h.get('battle-hud').children.flatMap(card=>card.children.filter(n=>n.className==='battle-mp-bar'));assert.equal(bars.length,2);assert.equal(bars[0].value,100);ui.next();assert.equal(f.state.battlePlayback.index,1);assert.equal(h.get('battle-next').disabled,true);h.get('battle-skip').onclick();h.get('battle-skip').onclick();assert.equal(commits,1);assert.equal(f.state.battlePlayback.done,true);assert.equal(normalize(f.state).battlePlayback.manual,true);}finally{h.close();}});
test('automatic mode still runs the precomputed timeline and speed does not change the outcome',()=>{const h=uiHarness(),f=battleFixture();let commits=0,ui;try{ui=mountBattleUI(f.state,{render:()=>ui.render(),persist(){},chat:{controls(){},isPending(){return false;},apply(){commits++;}},assetBase:'/'});ui.start(f.scene);h.get('battle-mode').onclick();assert.equal(f.state.battlePlayback.manual,false);for(let i=0;i<20;i++)h.clock(i*2000+1);assert.equal(commits,1);assert.equal(f.state.battlePlayback.index,f.scene.battle.events.length);}finally{h.close();}});
test('next action resumes a paused reading turn and waits again without automatically continuing',()=>{const h=uiHarness(),f=battleFixture();let ui;try{ui=mountBattleUI(f.state,{render:()=>ui.render(),persist(){},chat:{controls(){},isPending(){return false;},apply(){}},assetBase:'/'});ui.start(f.scene);h.clock(1);h.clock(1501);h.get('battle-pause').onclick();assert.equal(f.state.battlePlayback.paused,true);h.get('battle-next').onclick();assert.equal(f.state.battlePlayback.paused,false);assert.equal(f.state.battlePlayback.index,1);h.clock(2001);h.clock(4001);h.clock(90001);assert.equal(f.state.battlePlayback.index,1);assert.equal(h.get('battle-next').disabled,false);}finally{h.close();}});
