import test from 'node:test';
import assert from 'node:assert/strict';
import {uiHarness} from './ui-harness.mjs';
import {mountChatUI} from '../web/chat-ui.js';
import {battleFixture} from './battle-fixtures.js';
function setup(){const h=uiHarness(),state=battleFixture().state;state.page='story';state.player.name='청명';state.scene={scene_id:'choice-scene',location:'솔브린 마을',time:'오후',dialogue:[{speaker:'세린',text:'어떻게 할까요?'}],choices:[{id:'first',text:'자신을 소개한다.'},{id:'second',text:'마을을 살펴본다.'}]};state.sceneIndex=0;const chat=mountChatUI(state,{render(){},persist(){},embedded:true});return {h,chat,state};}
test('choice click sends the matching GPT action; an error unlocks choices and preserves the action',()=>{const {h}=setup();try{const button=h.get('scene-choices').children[0];button.onclick();let actions=h.messages.filter(m=>m.type==='action');assert.equal(actions.length,1);assert.match(actions[0].payload.text,/자신을 소개한다/);assert.equal(button.disabled,true);button.onclick();assert.equal(h.messages.filter(m=>m.type==='action').length,1);h.reply('action-error','GPT 입력 전달 실패');assert.equal(button.disabled,false);assert.equal(h.get('free-action').value,'자신을 소개한다.');button.onclick();assert.equal(h.messages.filter(m=>m.type==='action').length,2);}finally{h.close();}});
test('number shortcuts send one choice, never trigger inside input or other tabs/title',()=>{const {h,state}=setup();try{h.key('2',{closest:()=>({})});assert.equal(h.messages.filter(m=>m.type==='action').length,0);state.page='map';h.key('2');assert.equal(h.messages.filter(m=>m.type==='action').length,0);state.page='story';h.game.dataset.title='active';h.key('2');assert.equal(h.messages.filter(m=>m.type==='action').length,0);h.game.dataset.title='closed';h.key('2');assert.match(h.messages.find(m=>m.type==='action').payload.text,/마을을 살펴본다/);h.key('2');assert.equal(h.messages.filter(m=>m.type==='action').length,1);}finally{h.close();}});
test('Enter sends and Shift+Enter/Korean composition never sends',()=>{const {h}=setup();try{const input=h.get('free-action');input.value='안녕';let prevented=0;input.keydown({key:'Enter',shiftKey:true,preventDefault(){prevented++;},currentTarget:input});input.keydown({key:'Enter',isComposing:true,preventDefault(){prevented++;},currentTarget:input});assert.equal(h.messages.filter(m=>m.type==='action').length,0);input.keydown({key:'Enter',preventDefault(){prevented++;},currentTarget:input});assert.equal(prevented,1);assert.equal(h.messages.filter(m=>m.type==='action').length,1);}finally{h.close();}});
test('legacy launcher still sends a new-game request without falsely claiming an attachment',()=>{const {h,chat}=setup();try{chat.setCampaignSettings({sha:'a'.repeat(40),paths:['BOOTSTRAP.md','WORLD.md'],files:{'BOOTSTRAP.md':'설정 시작 안내','WORLD.md':'공식 세계관'}});chat.submit('안녕');const action=h.messages.find(m=>m.type==='action');assert.ok(action);assert.equal(action.payload.settingsFile,undefined);assert.match(action.payload.text,/파일 자동 첨부를 지원하지/);assert.match(action.payload.text,/raw.githubusercontent.com/);assert.equal(chat.isPending(),true);h.reply('action-error','테스트 종료');}finally{h.close();}});
test('invalid GPT scene immediately releases pending controls instead of silently blocking future messages',()=>{const {h,chat}=setup();try{chat.submit('안녕');assert.equal(chat.isPending(),true);chat.apply('{"type":"ercedia_scene","schema_version":99}');assert.equal(chat.isPending(),false);assert.equal(h.get('send-action').disabled,false);assert.match(h.get('connection-detail').textContent,/응답 적용 실패/);}finally{h.close();}});
test('all four number choices send their current text once after state refresh, and failures permit retries',()=>{const {h,state,chat}=setup();try{state.scene.choices=[1,2,3,4].map(i=>({id:'choice-'+i,text:'선택 '+i}));for(let i=1;i<=4;i++){chat.controls();h.key(String(i));const actions=h.messages.filter(m=>m.type==='action');assert.equal(actions.length,i);assert.ok(actions.at(-1).payload.text.endsWith('선택 '+i));h.reply('action-error','검증 종료');assert.equal(h.get('scene-choices').children[i-1].disabled,false);}}finally{h.close();}});
