import test from 'node:test';import assert from 'node:assert/strict';import {defaults,normalize} from '../web/state.js';import {initialPlayer} from '../web/intro-model.js';import {planEngineScene} from '../web/engine-model.js';import {eligibleSkills,equipSkill,equippedSkills} from '../web/skill-loadout.js';
const start=()=>({...defaults(),player:initialPlayer('단조 수련생'),gameState:{region:'W1',place:'광산 작업장',date:'650-07-01',time:'09:00'}});
const skill={id:'GM-SKILL-forging-01',name:'초급 단조',description:'가열된 철의 색과 망치 각도를 구분한다. 기본 작업장에서 연철 성형에 가벼운 이점. 희귀 장비 자동 제작은 불가.',skill_type:'passive',usage:'dialogue'};
const learn={event_id:'forge-learn',kind:'learn_custom_skill',reason:'장인의 지도로 가열과 망치질을 실제 반복하고 연철 성형을 성공했다.',skill};
const practice=(id='forge-practice')=>({event_id:id,kind:'practice',reason:'30분간 단조 자세를 반복해 실제 성형 성과를 냈다.',activity:'craft',completed:true,xp_gain:10});
test('actual forging earns XP and a custom skill, persists, equips and cannot reward twice',()=>{const s=start(),original=JSON.stringify(s);const scene={game_state:{time:'09:30'},engine_events:[practice(),learn]};const result=planEngineScene(s,scene,null);assert.equal(JSON.stringify(s),original);Object.assign(s,result);Object.assign(s.gameState,scene.game_state);assert.equal(s.player.xp,10);assert.equal(s.player.skills.length,1);assert.equal(s.player.skills[0].source,'gm');const restored=normalize(JSON.parse(JSON.stringify(s)));assert.equal(restored.player.skills[0].learning_reason,learn.reason);assert.equal(eligibleSkills(restored,'dialogue')[0].id,skill.id);equipSkill(restored,'dialogue',skill.id,0);assert.equal(equippedSkills(restored,'dialogue')[0].name,'초급 단조');const twice=planEngineScene(s,{game_state:{time:'10:00'},engine_events:[practice(),learn]},null);assert.equal(twice.player.xp,10);assert.equal(twice.player.skills.length,1);});
test('same-day easy practice diminishes and actual elapsed time and no-double-XP are required',()=>{const s=start();Object.assign(s,planEngineScene(s,{game_state:{time:'09:30'},engine_events:[practice()]},null));s.gameState.time='09:30';Object.assign(s,planEngineScene(s,{game_state:{time:'10:00'},engine_events:[practice('again')]},null));assert.equal(s.player.xp,15);const before=JSON.stringify(s);for(const scene of [{engine_events:[practice('no-time')]},{game_state:{time:'10:30'},engine_events:[practice('double'),{event_id:'xp',kind:'xp',amount:10,reason:'다시 지급'}]},{game_state:{time:'10:30'},engine_events:[{...practice('fake'),completed:false}]}])assert.throws(()=>planEngineScene(s,scene,null));assert.equal(JSON.stringify(s),before);});
test('custom learning rejects catalog ID forgery, ultimate injection and conflicting effects atomically',()=>{const s=start();Object.assign(s,planEngineScene(s,{engine_events:[learn]},null));const before=JSON.stringify(s);for(const value of [{...skill,id:'ER-SKILL-01'},{...skill,ultimate:true},{...skill,description:'무조건 신물 제작'}])assert.throws(()=>planEngineScene(s,{engine_events:[{...learn,event_id:'different',skill:value}]},null));assert.equal(JSON.stringify(s),before);});

test('learning a custom skill does not silently equip it or change basic stats',()=>{const s=start(),stats=['strength','dexterity','intelligence','constitution','manaStat'].map(k=>s.player[k]);Object.assign(s,planEngineScene(s,{engine_events:[learn]},null));assert.equal(equippedSkills(s,'dialogue').some(p=>p.id===skill.id),false);assert.deepEqual(['strength','dexterity','intelligence','constitution','manaStat'].map(k=>s.player[k]),stats);});

test('meaningful practice levels up through the existing +3 point rule and resets daily repetition',()=>{const s=start();s.player.xp=95;Object.assign(s,planEngineScene(s,{game_state:{time:'09:30'},engine_events:[practice()]},null));s.gameState.time='09:30';assert.equal(s.player.level,2);assert.equal(s.player.xp,5);assert.equal(s.player.unspentStatPoints,3);const result=planEngineScene(s,{game_state:{date:'650-07-02',time:'09:30'},engine_events:[practice('next-day')]},null);assert.equal(result.player.xp,15);});
