import test from 'node:test';
import assert from 'node:assert/strict';
import {planNPCLife,publicLife,lifeContext,lifeRole,regionImpact} from '../web/npc-life.js';
import {battleFixture} from './battle-fixtures.js';
import {mountChatUI} from '../web/chat-ui.js';
import {uiHarness} from './ui-harness.mjs';
import {placedNPCs} from '../web/character-art.js';
import {npcSnapshot} from '../web/npc-model.js';
import {defaults,normalize} from '../web/state.js';
import {normalizeScene,actionPrompt} from '../web/scene.js';
const make=(n,extra={})=>({schema_version:1,type:'ercedia_scene',scene_id:'life-'+n,location:'솔브린 마을',time:'오후',background_id:null,npc:{id:'serin',outfit:'armor',emotion:'base',speaker:'세린'},dialogue:[{speaker:'세린',text:'안녕하세요.'}],choices:[],game_state:{date:'1-1-1',region:'W3',place:'솔브린 마을'},...extra});
const start=()=>({...defaults(),gameState:{date:'1-1-1',region:'W3',place:'솔브린 마을'}});
const event=(kind,extra={})=>({event_id:kind+'-1',kind,date:'1-1-1',source_id:'scene:life-1',reason:'실제 사건의 GM 판정',...extra});
const apply=(s,x,q=null)=>{Object.assign(s,planNPCLife(s,normalizeScene(x),q));if(x.game_state)Object.assign(s.gameState,x.game_state);s.scene=normalizeScene(x);};
test('first encounter, affection and reunion retain structured memories; duplicate payload is idempotent',()=>{
  const s=start(),e=event('experience',{npc_id:'serin',action:'주민을 도왔다',result:'순찰을 도왔다',location:'솔브린 마을',follow_up:'협조적인 여행자로 기억',player_witnessed:true,affection_delta:12,participants:['serin']});
  const x=make(1,{life_events:[e]});apply(s,x);apply(s,x);assert.equal(s.relationships.serin.affection,12);assert.equal(s.npc_life.memories.length,2);apply(s,make(2));assert.match(actionPrompt(s,'재회','id'),/순찰을 도왔다/);assert.ok(publicLife(s,'serin').memories.some(m=>m.action==='첫 만남'));
});
test('confirmed movement prevents appearance at the previous place and preserves the original state on failure',()=>{
  const s=start();apply(s,make(1,{npc:null,life_events:[event('move',{npc_id:'serin',region:'W3',place:'마을 경비초소',activity:'경비'})]}));const snapshot=JSON.stringify(s);assert.throws(()=>apply(s,make(2)),/이전 장소/);assert.equal(JSON.stringify(s),snapshot);apply(s,make(3,{location:'마을 경비초소',game_state:{date:'1-1-1',region:'W3',place:'마을 경비초소'}}));
});
test('game days update important NPC schedules only; readings do not advance time',()=>{
  const s=start();apply(s,make(1,{life_events:[event('schedule',{npc_id:'serin',entries:[{start:'1-1-3',end:'1-1-5',region:'W3',place:'순찰길',activity:'순찰'}]})]}));assert.equal(s.npc_life.npcs.serin.destination,'순찰길');apply(s,make(2,{npc:null,game_state:{date:'1-1-3',region:'W3',place:'솔브린 마을'}}),{quest_log:[{id:'q',issuer_npc_id:'serin',status:'active',title:'순찰 지원'}],relationships:{},quest_event_ids:[]});assert.equal(s.npc_life.npcs.serin.place,'순찰길');assert.equal(Object.keys(s.npc_life.npcs).length,1);assert.throws(()=>apply(s,make(3)),/시간 역행/);
});
test('cross-kingdom movement requires an open legal checkpoint and valid explicit NPC permit',()=>{
  const s=start(),move=event('move',{npc_id:'serin',region:'E3',place:'동부 검문소',activity:'공식 연락'});assert.throws(()=>apply(s,make(1,{npc:null,life_events:[move]})),/국경/);move.border={route:'BORDER-WE-01',open:true,approved:true,permit_id:'permit-1',issuer_id:'ER-CORE-001',authority:'왕실 공식 연락 임무',purpose:'연락',valid_until:'1-1-5'};apply(s,make(1,{npc:null,life_events:[move]}));assert.equal(s.npc_life.npcs.serin.region,'E3');
});
test('rumors require a knowledgeable sender and arrive later; player journal excludes private NPC memories',()=>{
  const s=start(),memory=event('experience',{npc_id:'serin',action:'교역로의 사건 목격',result:'수레가 멈춤',location:'솔브린 마을',player_witnessed:false,affection_delta:0,participants:[]}),rumor=event('rumor',{event_id:'rumor-1',memory_id:'experience-1',from_npc:'serin',to_npc:'ER-NPC-001',channel:'military',message:'길목에 수레가 멈췄다고 한다',arrives_at:'1-1-3'});apply(s,make(1,{npc:null,life_events:[memory,rumor]}));assert.equal(s.npc_life.rumors[0].delivered,false);assert.equal(publicLife(s,'serin').memories.length,0);apply(s,make(2,{npc:null,game_state:{date:'1-1-3',region:'W3',place:'솔브린 마을'}}));assert.equal(s.npc_life.rumors[0].delivered,true);assert.equal(s.relationships['ER-NPC-001'],undefined);
});
test('quest state changes produce memories and single affection; condition and companions persist',()=>{
  const s=start(),e=event('companion',{npc_id:'serin',accompanying:true}),condition=event('condition',{npc_id:'serin',injuries:['팔의 타박상'],fatigue:'tired',major_event:null});apply(s,make(1,{life_events:[e,condition]}),{quest_log:[{id:'q',issuer_npc_id:'serin',status:'accepted',title:'순찰 지원'}],relationships:{serin:{affection:20,flags:[],interaction_history:[]}},quest_event_ids:['accept-q']});assert.equal(s.relationships.serin.affection,20);assert.equal(s.npc_life.npcs.serin.accompanying,true);assert.equal(s.npc_life.npcs.serin.fatigue,'tired');assert.deepEqual(normalize(s).npc_life,s.npc_life);assert.equal(publicLife(s,'serin').quests[0],'q');
});
test('region traces need actual structured world proof and event IDs cannot change content',()=>{
  const s=start(),e=event('region_effect',{source_id:'clear-road',region:'W3',effect:'도적 토벌로 길목 치안 개선',changes:{security:4,tradeRisk:-3},player_known:true});assert.throws(()=>apply(s,make(1,{life_events:[e]})),/선행 사건/);const scene=make(1,{npc:null,life_events:[e],world_events:[{event_id:'clear-road',kind:'action',target_id:'road',location:'솔브린 마을',proof:'현지 경비의 실제 토벌 기록'}]});apply(s,scene);apply(s,scene);assert.equal(s.npc_life.traces.length,1);assert.throws(()=>apply(s,{...scene,life_events:[{...e,effect:'변조'}]}),/내용 변경/);
});
test('NPC relationships are event facts, not extra player relation numbers; legacy saves retain shape',()=>{
  const s=start();apply(s,make(1,{life_events:[event('npc_relation',{from_npc:'serin',to_npc:'ER-NPC-001',relation:'경비 협력',player_known:false})]}));assert.equal(s.npc_life.links[0].relation,'경비 협력');assert.equal(lifeContext(s).constraints.includes('수신 완료'),true);assert.equal(normalize(defaults()).npc_life,undefined);assert.equal(s.relationships.serin,undefined);
});
test('battle settlement leaves memory exactly once and does not attribute protagonist injuries to every NPC',()=>{const f=battleFixture();const s={...f.state,gameState:{date:'1-1-1',region:'W3'}};const scene={...f.scene,game_state:{...f.scene.game_state,date:'1-1-1',region:'W3'}};apply(s,scene);apply(s,scene);assert.equal(s.npc_life.memories.length,1);assert.equal(s.npc_life.npcs.serin.activity,'전투불능');assert.deepEqual(s.npc_life.npcs.serin.injuries,[]);assert.equal(lifeRole('serin'),'knight');});
test('actual chat application validates all NPC effects before player or inventory mutations',()=>{const h=uiHarness(),s=start();s.player.name='검증';try{const chat=mountChatUI(s,{embedded:true,render(){},persist(){}});const old=JSON.stringify(s);chat.apply(JSON.stringify(make(1,{player:{...s.player,hp:1},life_events:[event('move',{npc_id:'serin',region:'E2',place:'공방',activity:'이동'})]})));assert.equal(JSON.stringify(s),old);assert.match(h.get('connection-detail').textContent,/국경/);chat.apply(JSON.stringify(make(2)));assert.equal(s.npc_life.memories[0].action,'첫 만남');}finally{h.close();}});
test('aliases cannot award the same cause twice and first meeting stays in long dialogue context',()=>{const s=start(),e=event('experience',{npc_id:'serin',action:'협조',result:'지원 확인',location:'솔브린 마을',player_witnessed:true,affection_delta:4,participants:[]});apply(s,make(1,{life_events:[e]}));assert.throws(()=>apply(s,make(2,{life_events:[{...e,event_id:'alias-event'}]})),/호감도 이중/);for(let i=0;i<60;i++)s.npc_life.memories.push({event_id:'later-'+i,npc_id:'serin',action:'기록',result:'연습',player_witnessed:true});assert.ok(lifeContext(s).memories.some(m=>m.action==='첫 만남'));assert.equal(s.relationships.serin.affection,4);});
test('regional deltas are stable, public-only reads hide undiscovered changes, and old saves keep affection only',()=>{const s=start(),e=event('region_effect',{source_id:'road-proof',region:'W3',effect:'길목 치안 개선',changes:{security:4,tradeRisk:-3},player_known:false});const x=make(1,{npc:null,life_events:[e],world_events:[{event_id:'road-proof',kind:'action',target_id:'road',location:'솔브린 마을',proof:'실제 경비 확인'}]});apply(s,x);apply(s,x);assert.deepEqual(regionImpact(s,'W3').changes,{security:4,tradeRisk:-3});assert.deepEqual(regionImpact(s,'W3',{publicOnly:true}).changes,{});s.relationships.serin={affection:-15,trust:99,familiarity:99};assert.equal(normalize(s).relationships.serin.affection,-15);assert.equal(normalize(s).relationships.serin.trust,undefined);});
test('new character placement UI and battle snapshot follow live movement, preserving approved art',()=>{const s=start(),e=event('move',{npc_id:'serin',region:'W4',place:'서부 경비초소',activity:'경비'});apply(s,make(1,{npc:null,life_events:[e]}));assert.ok(!placedNPCs('W3',null,s).some(p=>p.id==='serin'));assert.ok(placedNPCs('W4',null,s).some(p=>p.id==='serin'));const n=npcSnapshot(s,'serin');assert.equal(n.location_id,'W4');assert.equal(n.placement.location_id,'W4');assert.equal(n.art.id,'serin');assert.equal(n.level,18);});
