import test from 'node:test';
import assert from 'node:assert/strict';
import {planWorldScene,emptyWorld,advanceCalendar} from '../web/world-engine.js';
import {engineData} from '../web/engine-data.js';
import {worldData} from '../web/world-data.js';
import {normalize} from '../web/state.js';
import {ensureEngine,investStat,equipItem,unequipItem,combatPreview,learnBook,usableSkills} from '../web/engine-model.js';
import {settleQuests} from '../web/quest-model.js';
import {uiHarness} from './ui-harness.mjs';
import {mountChatUI} from '../web/chat-ui.js';
import {confirmedMonsterBattle} from './world-fixtures.js';
import {normalizeScene} from '../web/scene.js';
import {validateBattleSettlement} from '../web/battle-model.js';
import {mountBattleUI} from '../web/battle-ui.js';
const fixture=()=>({version:1,player:{name:'검증 여행자',job:'검사',level:1,hp:80,maxHp:100,mp:90,maxMp:100,xp:0,requiredXp:100,strength:10,dexterity:10,intelligence:10,constitution:10,manaStat:10,realm:'none',levelHpBonus:0,unspentStatPoints:3,skills:[]},inventory:[],gameState:{date:'1-1-1',region:'W1',place:'검증 장터'},currency:1000,seenScenes:[]});
let seq=0;
const event=(kind,fields={})=>({event_id:'ordered-'+ ++seq,kind,reason:'검증 GM의 실제 사건 판정',...fields});
const scene=(s,events,extra={})=>({schema_version:1,type:'ercedia_scene',scene_id:'ordered-scene-'+ ++seq,npc:null,background_id:null,dialogue:[{speaker:'나레이션',text:'검증된 행동 결과'}],choices:[],location:s.gameState.place,time:'오후',game_state:{...s.gameState},system_events:events,...extra});
const apply=(s,sc)=>{const p=planWorldScene(s,sc);if(p){s.world_engine=p.world_engine;s.currency=p.currency;if(p.scene.player)s.player=p.scene.player;if(p.scene.inventory)s.inventory=p.scene.inventory;Object.assign(s.gameState,p.scene.game_state);}return p;};
const battle=(id='battle-ordered')=>({battle_id:id,participants:[{id:'ER-NPC-081',side:'enemy'}],outcome:{winner:'allied',xp_gain:0,items_added:[],resources:[{id:'ER-NPC-081',hp:0,mp:0}]}});
const completed=(s,b)=>{s.battlePlayback={done:true,scene:{battle:b}};s.battleApplied=[b.battle_id];};
test('01 stat investment obeys 1/2/4 cost and preserves HP damage/MP spent',()=>{for(const [stat,cost]of [[50,1],[51,2],[101,4]]){const s=fixture();s.player.manaStat=stat;s.player.maxMp=100+6*(stat-10);s.player.mp=s.player.maxMp-10;s.player.unspentStatPoints=cost;investStat(s,'manaStat');assert.equal(s.player.mp,s.player.maxMp-10);assert.equal(s.player.unspentStatPoints,0);assert.equal(s.player.hp,80);}});
test('02 all 300 catalog equipment entries equip/unequip without stacking or free healing',()=>{assert.equal(engineData.equipment.length,300);for(const cat of engineData.equipment){const s=fixture();s.player.level=100;s.player.job=cat.equip_class;s.inventory=[{id:cat.id,name:cat.name,quantity:1}];const e=ensureEngine(s),before=combatPreview(s);equipItem(s,e.instances[0].instance_id);const once=combatPreview(s);equipItem(s,e.instances[0].instance_id);assert.deepEqual(combatPreview(s),once);assert.equal(s.player.maxHp-s.player.hp,20);unequipItem(s,cat.slot);assert.deepEqual(combatPreview(s),before);assert.equal(s.player.mp,90);}});
test('03 all 70 books can be learned; a lost book never erases an enabled learned skill',()=>{const s=fixture();s.player.level=100;ensureEngine(s).registration={circle:9};for(const b of engineData.books){s.player.job=b.required_class;s.inventory.push({id:b.id,name:b.name,quantity:1});learnBook(s,b.id,'등록 기술서 읽기와 실제 연습 확인');}assert.equal(s.player.skills.length,70);assert.equal(normalize(s).player.skills.length,70);s.inventory=[];assert.ok(usableSkills(s).length>0);});
test('04 confirmed loot grants registered materials once; wrong monster, dead state and quantity fail atomically',()=>{const s=fixture(),b=battle();completed(s,b);const e=event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-081',items:[{id:'MAT-001-1',quantity:2}]}),sc=scene(s,[e]);apply(s,sc);assert.equal(s.inventory[0].quantity,2);apply(s,sc);assert.equal(s.inventory[0].quantity,2);const before=structuredClone(s);assert.throws(()=>planWorldScene(s,scene(s,[event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-082',items:[]})])),/마수/);assert.deepEqual(s,before);assert.throws(()=>planWorldScene(fixture(),scene(fixture(),[event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-081',items:[{id:'MAT-001-1',quantity:3}]})],{battle:b})),/수량/);});
test('04 no-drop ruling is persisted and full inventory refuses the entire reward',()=>{const s=fixture(),b=battle();completed(s,b);apply(s,scene(s,[event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-081',items:[]})]));assert.equal(s.inventory.length,0);assert.equal(Object.keys(s.world_engine.loot_claims).length,1);const full=fixture();full.inventory=Array.from({length:32},(_,i)=>({id:'test-'+i,name:'보유품 '+i,quantity:1}));completed(full,b);const before=structuredClone(full);assert.throws(()=>planWorldScene(full,scene(full,[event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-081',items:[{id:'MAT-001-1',quantity:1}]})])),/가득/);assert.deepEqual(full,before);});
function enter(s){const d=worldData.dungeons[0];s.gameState.place=d.id;apply(s,scene(s,[event('discover_dungeon',{dungeon_id:d.id}),event('enter_dungeon',{dungeon_id:d.id,run_id:'run-first'})]));return d;}
function resolveAll(s,d){for(const z of d.zones){if(s.world_engine.dungeons[d.id].zone_id!==z.id)apply(s,scene(s,[event('enter_zone',{dungeon_id:d.id,zone_id:z.id})]));if(z.type==='entrance'){const proof={event_id:'proof-entry',kind:'action',target_id:z.id,location:d.id,proof:'실제 입구 정찰 완료'};apply(s,scene(s,[event('resolve_zone',{dungeon_id:d.id,zone_id:z.id,evidence_id:proof.event_id})],{world_events:[proof]}));}else {const b=battle('battle-'+z.id);completed(s,b);apply(s,scene(s,[event('resolve_zone',{dungeon_id:d.id,zone_id:z.id,battle_id:b.battle_id})]));}}}
test('05 all 26 layouts/108 zones exist, locked zones reject, retreat preserves resources and run',()=>{assert.equal(worldData.dungeons.length,26);assert.equal(worldData.dungeons.flatMap(d=>d.zones).length,108);const s=fixture(),d=enter(s);assert.throws(()=>planWorldScene(s,scene(s,[event('enter_zone',{dungeon_id:d.id,zone_id:d.boss_zone_id})])),/앞선/);apply(s,scene(s,[event('retreat',{dungeon_id:d.id})],{location:'검증 장터',game_state:{...s.gameState,place:'검증 장터'}}));assert.equal(s.world_engine.active_dungeon,null);assert.equal(s.player.hp,80);s.gameState.place=d.id;apply(s,scene(s,[event('enter_dungeon',{dungeon_id:d.id,run_id:'run-first'})]));assert.equal(s.world_engine.active_dungeon,d.id);});
test('06 first clear grants canonical XP/material once, derives actual quest proof, and save keeps claims',()=>{const s=fixture(),d=enter(s);resolveAll(s,d);const e=event('clear_dungeon',{dungeon_id:d.id,battle_id:s.world_engine.dungeons[d.id].boss_battle_id,material_id:'MAT-001-1'}),p=apply(s,scene(s,[e]));assert.equal(s.player.xp,93);assert.equal(s.inventory[0].quantity,1);assert.equal(p.scene.world_events[0].kind,'dungeon_clear');const restored=normalize(s);assert.equal(restored.world_engine.dungeons[d.id].claimed,true);assert.throws(()=>planWorldScene(s,scene(s,[event('clear_dungeon',{...e,event_id:'duplicate-clear'})])),/탐험/);assert.equal(s.player.xp,93);});
test('06 same boss fight cannot resolve two zones and repeat clear requires later respawn evidence',()=>{const s=fixture(),d=enter(s);resolveAll(s,d);apply(s,scene(s,[event('clear_dungeon',{dungeon_id:d.id,battle_id:s.world_engine.dungeons[d.id].boss_battle_id,material_id:'MAT-001-1'})]));assert.throws(()=>planWorldScene(s,scene(s,[event('respawn',{dungeon_id:d.id,evidence_id:'fake'})])),/재출현/);s.gameState.date='1-1-2';const proof={event_id:'respawn-proof',kind:'action',target_id:d.id,location:d.id,proof:'후속 현장 조사로 실제 마수 재출현 확인'};apply(s,scene(s,[event('respawn',{dungeon_id:d.id,evidence_id:proof.event_id})],{world_events:[proof]}));assert.equal(s.world_engine.dungeons[d.id].resolved.length,0);assert.equal(s.world_engine.dungeons[d.id].claimed,true);});
test('07 engine loot increases real gather objectives without paying a quest twice',()=>{const s=fixture(),b=battle();s.quest_log=[{id:'material-quest',title:'재료 조사',type:'gather',origin:'personal_npc',status:'active',rank:'F',region_id:'W1',issuer_name:'검증 의뢰인',objectives:[{id:'material',description:'실제 재료 확보',target:1,current:0,verification:{kind:'gather',target_id:'MAT-001-1'}}],reward:{xp:0,currency:0,item_ids:[],materials:[],affection_effects:[]}}];completed(s,b);const p=planWorldScene(s,scene(s,[event('loot',{battle_id:b.battle_id,monster_id:'ER-NPC-081',items:[{id:'MAT-001-1',quantity:1}]})]));const result=settleQuests(s,p.scene);assert.equal(result.quest_log[0].status,'ready_to_report');});
test('09 a party requires real accompanying local living NPCs and includes them in the battle',()=>{const s=fixture();s.gameState={date:'1-1-1',region:'W3',place:'솔브린 마을'};s.npc_life={npcs:{serin:{accompanying:true,region:'W3',place:'솔브린 마을'}}};apply(s,scene(s,[event('party',{members:['serin']})]));assert.deepEqual(s.world_engine.party,['serin']);assert.throws(()=>planWorldScene(s,scene(s,[],{battle:battle()})),/동료/);s.npc_life.npcs.serin.accompanying=false;assert.throws(()=>planWorldScene(s,scene(s,[event('party',{members:['serin']})])),/동행/);});
test('10 reputations are independent, origin starts at +10, duplicate event does not add again',()=>{const s=fixture();s.starting_kingdom='벨로아';s.world_engine=emptyWorld(s);assert.deepEqual(s.world_engine.kingdom_reputation,{west:10,east:0,south:0});const e=event('reputation',{kingdom:'east',delta:25}),sc=scene(s,[e]);apply(s,sc);apply(s,sc);assert.equal(s.world_engine.kingdom_reputation.east,25);assert.equal(s.world_engine.kingdom_reputation.west,10);assert.equal(normalize(s).world_engine.kingdom_reputation.east,25);});
test('10 an actual cross-country move requires open route, valid permit and first-visit guarantor',()=>{const s=fixture();s.starting_kingdom='벨로아';s.world_engine=emptyWorld(s);s.gameState.region='W4';const dest={...s.gameState,region:'E3',place:'검문소 동쪽'};assert.throws(()=>planWorldScene(s,scene(s,[],{game_state:dest})),/검문/);const p=event('permit',{permit:{id:'permit-east',kingdom:'east',issuer_id:'serin',authority:'검증 GM이 실제 발급 권한을 확인',purpose:'방문',valid_from:'1-1-1',valid_until:'1-2-1',guarantor:'현지 공인 보증인'}}),b=event('border',{route_id:'BORDER-WE-01',to:'east',result:'passed',open:true,permit_id:'permit-east'});apply(s,scene(s,[p,b],{game_state:dest}));assert.equal(s.world_engine.border_crossing_history[0].result,'passed');assert.equal(s.gameState.region,'E3');});
const offer=()=>({id:'quote-1',type:'shop',venue_id:'test-market',venue_name:'검증 장터',region_id:'W1',valid_until:'1-1-3',items:[{id:'ER-EQ-001',stock:2,buy_price:100,sell_price:40,price_basis:'고정 가격이 아닌 검증 GM의 당일 현지 견적'}]});
test('12 buying/selling debits gold and changes stock/inventory once; insufficient gold is atomic',()=>{const s=fixture();apply(s,scene(s,[event('offer',{offer:offer()})]));const e=event('trade',{offer_id:'quote-1',item_id:'ER-EQ-001',quantity:1,direction:'buy'}),sc=scene(s,[e]);apply(s,sc);apply(s,sc);assert.equal(s.currency,900);assert.equal(s.inventory[0].quantity,1);assert.equal(s.world_engine.offers['quote-1'].items[0].stock,1);apply(s,scene(s,[event('trade',{offer_id:'quote-1',item_id:'ER-EQ-001',quantity:1,direction:'sell'})]));assert.equal(s.currency,940);assert.equal(s.inventory.length,0);s.currency=0;const before=structuredClone(s);assert.throws(()=>planWorldScene(s,scene(s,[event('trade',{offer_id:'quote-1',item_id:'ER-EQ-001',quantity:1,direction:'buy'})])),/재화/);assert.deepEqual(s,before);});
test('11 an actual registered facility consumes quote materials/gold and produces its quoted item',()=>{const s=fixture(),f=worldData.facilities.find(f=>f.region_id==='W1'&&f.service.includes('smithing'));s.gameState.place=f.id;s.inventory=[{id:'MAT-001-1',name:'서리갈기 가죽',category:'material',quantity:2}];const o={...offer(),id:'smith-quote',type:'facility',venue_id:f.id,venue_name:f.name,items:[],services:[{id:'smith-work',service:'smithing',cost:30,basis:'GM의 실제 현지 제작 견적',inputs:[{id:'MAT-001-1',quantity:1}],outputs:[{id:'ER-EQ-001',quantity:1}]}]};apply(s,scene(s,[event('offer',{offer:o}),event('service',{offer_id:o.id,service_id:'smith-work'})]));assert.equal(s.currency,970);assert.equal(s.inventory.find(i=>i.id==='MAT-001-1').quantity,1);assert.equal(s.inventory.find(i=>i.id==='ER-EQ-001').quantity,1);assert.equal(s.world_engine.facility_history[0].facility_id,f.id);});
test('12 auction escrow reserves only bid increases; lost auction refunds exactly once',()=>{const s=fixture(),a={id:'auction-1',item_id:'ER-EQ-001',venue_id:'test-market',venue_name:'검증 장터',region_id:'W1',reserve:50,closes_at:'1-1-2',price_basis:'검증 GM의 실제 경매 공고',eligible:true};apply(s,scene(s,[event('auction',{auction:a}),event('bid',{auction_id:a.id,amount:70}),event('bid',{auction_id:a.id,amount:90})]));assert.equal(s.currency,910);assert.equal(s.world_engine.auctions[a.id].escrow,90);assert.equal(s.inventory.length,0);s.gameState.date='1-1-2';const e=event('auction_result',{auction_id:a.id,result:'lost'}),sc=scene(s,[e]);apply(s,sc);apply(s,sc);assert.equal(s.currency,1000);assert.equal(s.world_engine.auctions[a.id].escrow,0);});
test('13 crossing a 360-day year boundary prepares actual annual candidates without forcing disasters',()=>{const w=emptyWorld();advanceCalendar(w,'1-12-30');advanceCalendar(w,'2-1-1');assert.equal(w.calendar.month_cursor,24);assert.equal(w.annual_events['2:annual-main-01'].status,'planned');const size=Object.keys(w.annual_events).length;advanceCalendar(w,'2-1-1');assert.equal(Object.keys(w.annual_events).length,size);assert.throws(()=>advanceCalendar(w,'1-12-30'),/역행/);});
test('13 GM-confirmed calendar effects persist once and private distant results remain unannounced',()=>{const s=fixture();s.world_engine=emptyWorld();apply(s,scene(s,[]));const e=event('calendar_result',{ref_id:'1:W1-01-1',status:'resolved',effects:{security:2},known_to_player:false}),sc=scene(s,[e]);apply(s,sc);apply(s,sc);assert.equal(s.world_engine.monthly_world_state['1-1'].regional_changes.W1.security,2);assert.equal(s.world_engine.annual_events[e.ref_id].public_summary,'');assert.equal(normalize(s).world_engine.annual_events[e.ref_id].status,'resolved');});
test('a failing second system event rolls back gold, inventory, calendar and all claims',()=>{const s=fixture(),before=structuredClone(s);assert.throws(()=>planWorldScene(s,scene(s,[event('reputation',{kingdom:'west',delta:20}),event('party',{members:['missing-npc']})])),/동行|동행/);assert.deepEqual(s,before);});
test('actual chat application saves a trade beside a quest without restoring the old currency; invalid later events change nothing',()=>{
  const h=uiHarness(),s=fixture();s.quest_log=[];let saves=0;
  const chat=mountChatUI(s,{render(){},persist(){saves++;},embedded:true});
  try{
    chat.apply(JSON.stringify(scene(s,[event('offer',{offer:offer()})])));
    // An offered quest forces the normal quest settlement branch on the next trade.
    s.quest_log=[{id:'open-quest',title:'현지 조사',type:'investigate',origin:'personal_npc',status:'offered',rank:'F',region_id:'W1',issuer_name:'검증 의뢰인',objectives:[{id:'clue',description:'단서',target:1,current:0,verification:{kind:'clue',target_id:'proof-1'}}],reward:{xp:0,currency:0,item_ids:[],materials:[],affection_effects:[]}}];
    chat.apply(JSON.stringify(scene(s,[event('trade',{offer_id:'quote-1',item_id:'ER-EQ-001',quantity:1,direction:'buy'})])));
    assert.equal(s.currency,900);assert.equal(s.inventory[0].id,'ER-EQ-001');assert.equal(saves,2);
    const before=structuredClone(s);chat.apply(JSON.stringify(scene(s,[event('reputation',{kingdom:'west',delta:20}),event('party',{members:['missing-npc']})])));
    assert.deepEqual(s,before);assert.equal(saves,2);assert.match(h.get('connection-detail').textContent,/응답 적용 실패/);
  }finally{h.close();}
});
test('04 individual monsters reuse registered source art/stats and never share a species death state',()=>{
  const s=fixture();s.player.hp=100;s.player.mp=100;s.npcStates={'ER-NPC-081':{hp:0}};ensureEngine(s).bonuses={potentials:{}};
  const b=confirmedMonsterBattle(s,{battleId:'instance-test',items:[{id:'MAT-001-1',quantity:1}]}),sc=normalizeScene(scene(s,[],b));
  assert.equal(sc.battle.participants[1].catalog_id,'ER-NPC-081');assert.equal(validateBattleSettlement(sc,s),true);
  const wrong=structuredClone(sc);wrong.battle.participants[1].stats.strength++;assert.throws(()=>validateBattleSettlement(wrong,s),/NPC/);
  const h=uiHarness();try{const ui=mountBattleUI(s,{render(){ui.render();},persist(){},chat:{controls(){},isPending(){return false;}}});ui.start(sc);const image=h.get('battle-right').children[0].children[0];assert.match(image.src,/ER-NPC-081/);}finally{h.close();}
});
test('11 a healing facility quote restores only the approved amount up to actual maximums',()=>{
  const s=fixture(),f=worldData.facilities.find(f=>f.region_id==='S1'&&f.service.includes('healing'));s.gameState.region='S1';s.gameState.place=f.id;
  const o={...offer(),id:'heal-quote',type:'facility',venue_id:f.id,venue_name:f.name,region_id:'S1',items:[],services:[{id:'heal',service:'healing',cost:25,basis:'검증 GM의 실제 치유 견적',hp_restore:10,mp_restore:20}]};
  apply(s,scene(s,[event('offer',{offer:o}),event('service',{offer_id:o.id,service_id:'heal'})]));assert.equal(s.player.hp,90);assert.equal(s.player.mp,100);assert.equal(s.currency,975);
});
