import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize} from '../web/state.js';
import {normalizeScene} from '../web/scene.js';
import {normalizeQuest,settleQuests,calendarDay,questMapPoint} from '../web/quest-model.js';
import {battleFixture} from './battle-fixtures.js';
export const quest=()=>({id:'quest-demo-1',title:'잿빛 곡창 입구 조사',summary:'세린이 실제 입구를 확인해 달라고 부탁한다.',type:'dungeon',origin:'personal_npc',region_id:'W3',issuer_npc_id:'serin',issuer_name:'세린',rank:'F',status:'offered',target_location_id:'DUN-W3-01',deadline_at:'1-1-10',objectives:[{id:'entry',description:'잿빛 곡창 입구 진입 확인',current:0,target:1,verification:{kind:'dungeon_enter',target_id:'DUN-W3-01'}}],reward:{xp:14,currency:5,item_ids:['ER-EQ-001'],materials:[],affection_effects:[{npc_id:'serin',delta:2,reason:'약속을 지켰다.'}]}});
export const scene=(id,extra={})=>({schema_version:1,type:'ercedia_scene',scene_id:id,location:'솔브린 마을',time:'오후',background_id:'sunny_village_day',npc:{id:'serin',outfit:'armor',emotion:'base',speaker:'세린'},dialogue:[{speaker:'세린',text:'의뢰를 함께 확인해봅시다.'}],choices:[],...extra});
export const questState=()=>({...battleFixture().state,gameState:{date:'1-1-1',region:'W3',place:'솔브린 마을'}});
function apply(s,raw){const parsed=normalizeScene(raw);Object.assign(s,settleQuests(s,parsed));if(parsed.game_state)Object.assign(s.gameState,parsed.game_state);return s;}
function active(){const s=questState();apply(s,scene('offer',{quest_updates:[quest()]}));apply(s,scene('accept',{quest_events:[{event_id:'accept-1',quest_id:'quest-demo-1',kind:'accept',reason:'세린의 실제 수락 확인'}]}));return s;}
function ready(){const s=active();apply(s,scene('enter',{location:'DUN-W3-01',game_state:{place:'DUN-W3-01'},world_events:[{event_id:'entered-1',kind:'dungeon_enter',target_id:'DUN-W3-01',location:'DUN-W3-01',proof:'실제 던전 입구 진입 저장'}]}));return s;}
test('personal proposal and GM acceptance are saved without paying or advancing from prose',()=>{const s=active();assert.equal(s.quest_log[0].status,'accepted');apply(s,scene('only-prose',{dialogue:[{speaker:'나레이션',text:'던전을 모두 조사했다.'}]}));assert.equal(s.quest_log[0].status,'active');assert.equal(s.quest_log[0].objectives[0].current,0);assert.equal(s.wallet_copper,0);});
test('actual registered dungeon entry advances and unrelated/wrong-location proof is refused',()=>{const s=ready();assert.equal(s.quest_log[0].status,'ready_to_report');const saved=structuredClone(s);assert.throws(()=>apply(s,scene('bad',{world_events:[{event_id:'bad-1',kind:'dungeon_clear',target_id:'DUN-W3-01',location:'타국',proof:'말뿐인 클리어'}]})),/장소/);assert.deepEqual(s,saved);});
test('report pays XP/items/currency/one affection once; duplicate claims cannot mutate snapshots',()=>{const s=ready(),beforeXp=s.player.xp;apply(s,scene('report',{game_state:{place:'솔브린 마을'},quest_events:[{event_id:'claim-1',quest_id:'quest-demo-1',kind:'report',reason:'세린에게 조사 결과를 전달하고 확인받음'}]}));assert.equal(s.quest_log[0].status,'completed');assert.equal(s.player.xp,beforeXp+14);assert.equal(s.wallet_copper,5);assert.equal(s.inventory.find(i=>i.id==='ER-EQ-001').quantity,1);assert.equal(s.relationships.serin.affection,2);const before=structuredClone(s);assert.throws(()=>apply(s,scene('repeat',{player:{...s.player,xp:99},quest_events:[{event_id:'claim-1',quest_id:'quest-demo-1',kind:'report',reason:'반복'}]})),/이미 적용/);assert.deepEqual(s,before);assert.deepEqual(normalize(s).quest_log,s.quest_log);assert.equal(normalize(s).relationships.serin.affection,2);});
test('report requires issuer, verified objectives and forbids GM double reward snapshots',()=>{const s=active();assert.throws(()=>apply(s,scene('premature',{quest_events:[{event_id:'premature',quest_id:'quest-demo-1',kind:'report',reason:'일을 안 했다'}]})),/실제 목표/);const r=ready();assert.throws(()=>apply(r,scene('wrong-person',{npc:null,quest_events:[{event_id:'wrong-person',quest_id:'quest-demo-1',kind:'report',reason:'발행자 아님'}]})),/발행자/);assert.throws(()=>apply(r,scene('double',{player:r.player,quest_events:[{event_id:'double',quest_id:'quest-demo-1',kind:'report',reason:'보상 포함'}]})),/스냅샷/);});
test('hunt derives proof only from settled battle and duplicate events do not advance twice',()=>{const f=battleFixture(),s=questState(),q=quest();q.type='hunt';q.objectives=[{id:'kill',description:'상대 전투불능',current:0,target:2,verification:{kind:'battle_win',target_id:'serin'}}];apply(s,scene('offer-hunt',{quest_updates:[q]}));apply(s,scene('accept-hunt',{quest_events:[{event_id:'accept-hunt',quest_id:q.id,kind:'accept',reason:'테스트 수락'}]}));apply(s,f.scene);assert.equal(s.quest_log[0].objectives[0].current,1);apply(s,{...f.scene,scene_id:'replay'});assert.equal(s.quest_log[0].objectives[0].current,1);assert.throws(()=>apply(s,scene('fake-battle',{world_events:[{event_id:'fake-battle',kind:'battle_win',target_id:'serin',location:'솔브린 마을',proof:'글로 처치'}]})),/전투 정산/);});
test('gather and delivery require actual registered inventory changes',()=>{const s=questState(),q=quest();q.type='gather';q.objectives=[{id:'gather',description:'서리갈기 가죽 수집',current:0,target:2,verification:{kind:'gather',target_id:'MAT-001-1'}}];apply(s,scene('offer-gather',{quest_updates:[q]}));apply(s,scene('accept-gather',{quest_events:[{event_id:'accept-gather',quest_id:q.id,kind:'accept',reason:'확인'}]}));apply(s,scene('acquired',{inventory:[{id:'MAT-001-1',name:'서리갈기 가죽',quantity:2,category:'material'}]}));assert.equal(s.quest_log[0].status,'ready_to_report');assert.throws(()=>apply(s,scene('fake-gather',{world_events:[{event_id:'fake-gather',kind:'gather',target_id:'MAT-001-1',location:'솔브린 마을',quantity:1,proof:'인벤토리 변화 없음'}]})),/재료 획득/);});
test('failed, abandoned, declined and 360-day expired states persist',()=>{for(const kind of ['fail','abandon']){const s=active();apply(s,scene(kind,{quest_events:[{event_id:kind,quest_id:'quest-demo-1',kind,reason:'실제 사건 확인'}]}));assert.equal(s.quest_log[0].status,kind==='fail'?'failed':'abandoned');assert.equal(normalize(s).quest_log[0].status,s.quest_log[0].status);}const s=active();apply(s,scene('deadline',{game_state:{date:'1-1-11'}}));assert.equal(s.quest_log[0].status,'expired');assert.equal(calendarDay('1-2-1')-calendarDay('1-1-30'),1);assert.equal(calendarDay('1-1-31'),null);assert.equal(questMapPoint(s.quest_log[0]).id,'W3');});
test('old saves show empty quest lists without losing exact legacy keys; conditions cannot change after acceptance',()=>{const s=questState();assert.equal(normalize(s).quest_log,undefined);const a=active(),before=structuredClone(a);assert.throws(()=>apply(a,scene('rewrite',{quest_updates:[{...quest(),reward:{xp:99999}}]})),/조건/);assert.deepEqual(a,before);});
