from pathlib import Path
from PIL import Image, ImageOps, ImageDraw, ImageFont
import json,hashlib,re
root=Path(__file__).resolve().parents[1]
plan_path=root/'artifacts/common-npcs/generation-plan.json'
plan=json.loads(plan_path.read_text(encoding='utf-8'))
rows=[]
for job in plan['jobs']:
    for kind,size in [('portrait',(1086,1448)),('standing',(1024,1536))]:
        path=root/job[kind+'_path']
        if not path.exists():continue
        image=Image.open(path).convert('RGBA')
        before={'size':image.size,'alpha_bbox':image.getchannel('A').getbbox()}
        # Standardize alpha noise and use lossless transparent padding, no redrawing.
        a=image.getchannel('A').point(lambda v:0 if v<=8 else 255 if v>=250 else v)
        image.putalpha(a)
        if kind=='standing':
            bbox=a.getbbox()
            if not bbox:raise RuntimeError('Empty character '+job['id'])
            if not job.get('aligned'):
                cut=image.crop(bbox)
                height=int(re.match(r'(\d+)',job['specification']['appearance']).group(1))
                target_height=round(1382*height/184)
                ratio=min(920/cut.width,target_height/cut.height)
                cut=cut.resize((round(cut.width*ratio),round(cut.height*ratio)),Image.Resampling.LANCZOS)
                image=Image.new('RGBA',size)
                image.alpha_composite(cut,((1024-cut.width)//2,1459-cut.height))
        elif not job.get('portrait_aligned'):
            cut=image.crop(a.getbbox())
            fitted=ImageOps.contain(cut,(998,1356),Image.Resampling.LANCZOS)
            image=Image.new('RGBA',size)
            image.alpha_composite(fitted,((size[0]-fitted.width)//2,46))
        # RGBA pixels outside the alpha silhouette carry no matte color.
        clean=Image.new('RGBA',image.size);clean.paste(image,(0,0));pixels=clean.load()
        for y in range(clean.height):
            for x in range(clean.width):
                r,g,b,a=pixels[x,y]
                if a==0:pixels[x,y]=(0,0,0,0)
        clean.save(path,optimize=True)
        a=clean.getchannel('A');bbox=a.getbbox();hist=a.histogram()
        margins=[bbox[0],bbox[1],size[0]-bbox[2],size[1]-bbox[3]]
        valid=clean.size==size and hist[0]>0 and hist[255]>0 and all(a.getpixel(p)==0 for p in [(0,0),(size[0]-1,0),(0,size[1]-1),(size[0]-1,size[1]-1)])
        if kind=='standing':valid=valid and margins[0]>=52 and margins[2]>=52 and margins[1]>=77 and margins[3]>=77
        rows.append({'id':job['id'],'name':job['name'],'kind':kind,'path':job[kind+'_path'],'size':size,'mode':clean.mode,'alpha_extrema':a.getextrema(),'transparent_pixels':hist[0],'opaque_pixels':hist[255],'bbox':bbox,'margins_left_top_right_bottom':margins,'temporary_anchor':[512,1459] if kind=='standing' else None,'source_metrics':before,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'passed':valid,'visual_review':'pending final contact-sheet review','approval':'pending_user_review'})
    if (root/job['standing_path']).exists():job['aligned']=True
    if (root/job['portrait_path']).exists():job['portrait_aligned']=True
plan_path.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
result={'count':len(rows),'expected':48,'files':rows,'all_present':len(rows)==48,'all_passed':len(rows)==48 and all(r['passed'] for r in rows),'method':'Source images generated by built-in image_gen; prior authorized general image processing standardizes alpha noise and pads/resizes without changing aspect ratio or redrawing. Standing scale retains roster height relative to184cm, common temporary foot anchor512,1459.'}
(root/'artifacts/common-npcs/validation.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
font_path=Path('C:/Windows/Fonts/malgun.ttf')
font=ImageFont.truetype(str(font_path),18)
for kingdom,label in [('west','벨로아'),('east','드라켄'),('south','루메린')]:
    group=[j for j in plan['jobs'] if j['specification']['kingdom_id']==kingdom]
    board=Image.new('RGB',(1600,860),'#202932');draw=ImageDraw.Draw(board)
    draw.text((24,12),f'{label} · 생활형 NPC 기본 초상화 / 전신 검수 시안',font=font,fill='#edddb5')
    for i,j in enumerate(group):
        x=(i%4)*400;y=55+(i//4)*390
        draw.text((x+14,y),j['id']+' '+j['name'],font=font,fill='#f4e9da')
        draw.text((x+14,y+27),j['job'],font=font,fill='#b6bfc6')
        for kind,left,box in [('portrait',14,(178,485)),('standing',205,(182,485))]:
            p=root/j[kind+'_path']
            if p.exists():
                im=Image.open(p).convert('RGBA');im.thumbnail(box,Image.Resampling.LANCZOS)
                board.paste(im,(x+left+(box[0]-im.width)//2,y+67),im)
    board.save(root/f'artifacts/common-npcs/{kingdom}-preview.jpg',quality=94)
print(json.dumps({'generated':len(rows),'failed':[r['id']+':'+r['kind'] for r in rows if not r['passed']]},ensure_ascii=False))
