import {actualPlace,adventureOptions,adventureGuide,questPreview,dungeonRewardPreview} from './adventure-model.js';
import {townPeople,townConversation} from './town-people.js';
import {characterVisual} from './character-art.js';
import {formatCopper} from './wallet.js';
import {catalogItem as engineItem} from './item-catalog.js';
export function mountAdventureUI(state,{submit,isPending,switchTo,assetBase=''}){
 const game=document.querySelector('.game'),open=document.createElement('button');
 open.type='button';open.textContent='마을·모험';document.querySelector('.utility-actions').append(open);
 const headers=[document.querySelector('.game-navigation')||document.querySelector('.tabs'),document.getElementById('play-hud')];
 function measureHeader(){if(!game.getBoundingClientRect)return;const top=game.getBoundingClientRect().top,bottom=Math.max(top,...headers.map(el=>el.getBoundingClientRect().bottom));game.style.setProperty('--story-header-height',Math.ceil(bottom-top)+'px');}
 if(typeof ResizeObserver==='function'){const observer=new ResizeObserver(measureHeader);for(const el of headers)observer.observe(el);}
 const panel=document.createElement('section');panel.className='adventure-modal';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','마을과 모험 행동');game.append(panel);
 let tab='home';const busy=()=>isPending()||!!state.introDraft||!!state.battlePlayback&&!state.battlePlayback.done;
 const add=(parent,tag,text,cls)=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el;};
 const button=(parent,label,action,disabled=false)=>{const b=add(parent,'button',label);b.type='button';b.disabled=disabled;b.onclick=action;return b;};
 function close(){panel.hidden=true;open.setAttribute('aria-expanded','false');open.focus({preventScroll:true});}
 function ask(action){if(busy())return;close();switchTo('story');const {region,place}=actualPlace(state);submit(`[마을·모험 행동] 현재 실제 위치 ${region||'미확인'} · ${place}. ${action} 장소 클릭은 이동·획득·회복 성공을 뜻하지 않습니다. 실제 접근 조건·시간·비용·위험을 확인하고 판정된 변경만 기존 engine_events/system_events/world_events/life_events/quest_events로 기록하세요.`);}
 function refresh(){const creating=!!state.introDraft,location=actualPlace(state),guide=adventureGuide(state);open.hidden=creating||!state.player.name||game.dataset.title==='active';open.disabled=busy();measureHeader();
  if(panel.hidden)return;if(creating||game.dataset.title==='active'){panel.hidden=true;return;}
  const options=adventureOptions(state);panel.replaceChildren();const header=add(panel,'div','','adventure-heading');add(header,'h2',location.place);button(header,'닫기',close);
  const nav=add(panel,'nav','','adventure-tabs');for(const [key,label]of [['home','다음 목표'],['people','주변 인물'],['board','일자리·의뢰'],['shop','상점'],['training','수련'],['rest','휴식'],['travel','마을 밖으로']]){const b=button(nav,label,()=>{tab=key;refresh();});b.setAttribute('aria-pressed',String(tab===key));}
  const body=add(panel,'div','','adventure-body');
  if(state.world_engine?.active_dungeon){add(body,'h3','던전 탐험 중');add(body,'p','마을 시설을 이용하려면 실제로 퇴각하고 귀환해야 합니다.');button(body,'현재 던전 구역 보기',()=>{close();switchTo('map');});button(body,'퇴각·귀환 요청',()=>ask(`${state.world_engine.active_dungeon} 던전에서 퇴각하고 안전한 장소로 귀환을 시도한다. 자동 치료나 보상 중복 지급 금지.`),busy());return;}
  if(tab==='home'){add(body,'h3',guide.title);add(body,'p',guide.detail);button(body,'목표 확인',()=>{if(guide.action==='board'){tab='board';refresh();}else{close();switchTo(guide.action);}});add(body,'p','준비 → 의뢰·탐험 → 획득 → 귀환·보고 → 성장·정비','adventure-loop');
   for(const [label,key,description]of [['일거리로 여비 마련','board','현재 지역의 조건·기한·보수를 비교하세요.'],['주변을 탐색','travel','등록된 탐험지와 위험도를 확인하세요.'],['주민과 인연 맺기','people','현재 만날 수 있는 인물의 활동을 살펴보세요.']]){const card=add(body,'article','','adventure-card');add(card,'h3',label);add(card,'p',description);button(card,'살펴보기',()=>{tab=key;refresh();});}}
  if(tab==='people'){
   add(body,'p','현재 위치가 확인된 인물만 직접 대화할 수 있습니다. 위치 미확인 주민은 주변 탐색에서 만난 뒤 대화할 수 있습니다.');
   for(const p of townPeople(state)){
    const card=add(body,'article','','adventure-card resident-card'),art=characterVisual(p.id);
    if(art){const img=document.createElement('img');img.src=assetBase+art.path;img.alt=p.job;img.loading='lazy';card.append(img);}
    add(card,'h3',p.job+' · '+p.name);add(card,'p',p.canTalk?p.activity+' · '+p.place:p.unavailableReason);
    const talk=button(card,p.canTalk?'만나서 대화':'지금은 만날 수 없음',()=>{const request=townConversation(state,p.id);if(request)ask(request);else refresh();},busy()||!p.canTalk);talk.title=p.unavailableReason;
   }
   button(body,'현지 주민·소식 알아보기',()=>ask('현재 장소에서 실제 만날 수 있는 생활형 주민과 공개 소식을 알아본다. 등록 NPC의 역할·현재 위치를 지키고 먼 지역의 비밀을 누설하지 않는다.'),busy());
  }
  if(tab==='board'){const log=(state.quest_log||[]).filter(q=>q.region_id===location.region&&['offered','accepted','active','ready_to_report'].includes(q.status));add(body,'p','의뢰 수락은 선택입니다. 버튼으로 조건을 확인하고 자유 입력으로 협상할 수 있습니다.');
   for(const q of log){const card=add(body,'article','','adventure-card'),v=questPreview(q,state);add(card,'h3',`[${q.rank||'등급 미정'}] ${q.title}`);add(card,'p',`${q.issuer_name} · ${v.progress}% · ${v.days===null?'기한 미정':v.days<0?'기한 경과':v.days+'일 남음'}`);const reward=`EXP +${v.reward.xp||0} · ${formatCopper(v.reward.currency||0)} · ${[...(v.reward.item_ids||[]).map(id=>engineItem(id)?.name||id),...(v.reward.materials||[]).map(m=>(engineItem(m.id)?.name||m.id)+' ×'+m.quantity)].join(', ')||'아이템 보상 없음'}`;add(card,'p',reward);const details=add(card,'details',''),summary=add(details,'summary','내용·목표·보상');add(details,'p',v.description);for(const o of q.objectives||[])add(details,'p',`${o.text||o.description||o.id} · ${o.current||0}/${o.target||1}`);add(details,'p',reward);card.title=v.description+'\n'+reward;button(card,q.status==='offered'?'수락 요청':q.status==='ready_to_report'?'발행자에게 보고':'목표 확인·진행',()=>ask(`의뢰 ${q.id} 「${q.title}」를 ${q.status==='offered'?'수락 요청':q.status==='ready_to_report'?'발행자에게 실제 보고':'목표와 실제 진행 경로를 확인'}한다. 조건과 실제 사건을 검사하고 승인된 의뢰 사건으로만 진행한다.`),busy());}
   if(!log.length)add(body,'p','아직 알려진 현지 의뢰가 없습니다. 게시 창구나 주민에게 조건을 물어보세요.');button(body,'현지 일자리·게시 창구 조회',()=>ask('현재 지역의 실제 게시 창구·주민에게 일자리와 가능한 의뢰를 묻는다. 현재 날짜·전쟁·마수·NPC 상황에 맞는 제안만 offered로 제시하고 목표·기한·위험·XP·재화·재료 보상을 명확히 안내한다. 공식 길드 지부를 새로 만들지 않는다.'),busy());button(body,'전체 의뢰 기록',()=>{close();switchTo('quests');});}
  if(tab==='training'){add(body,'h3','기초 단련');add(body,'p','안전한 현 위치에서 무리하지 않는 단련 1회. 시간·성과·경험치 여부는 현재 상태와 수련 규칙에 따라 판정합니다.');button(body,'기초 단련 1회 실행',()=>ask('현재 안전한 장소에서 무리하지 않는 개인 기초 단련 1회를 실행한다. 통상적인 소요 시간과 실제 성과는 GM이 판정한다. 지도자·유료 시설·새 장비 없이 가능한 범위에서 진행하고 승인되지 않은 비용은 지출하지 않는다. 실행 가능하면 game_state.date/time에 시간을 반영하고 실제 수련 성과는 engine_events practice로 활동·완료·판정 XP를 한 번 기록하고 새 기술을 익혔다면 learn_custom_skill로 기록한다. 경험치를 얻지 못했다면 구체적 이유를 설명한다. 체력·장소 때문에 원래 방식이 막히면 안전한 휴식·대체 방법을 짧게 마련하고 같은 응답에서 가능한 단련과 결과까지 처리한다. 능력치·경지를 직접 올리거나 실행 중·미확정이라는 문장만 출력하지 않는다.'),busy()||state.player.hp===0);}
  if(tab==='shop'||tab==='training'){const services=options.facilities.filter(f=>tab==='shop'?/상점|거래|대장|장비|서고|시장/.test(f.name+' '+f.description):/훈련|수련|교육|마법|서고/.test(f.name+' '+f.description));for(const f of services){const card=add(body,'article','','adventure-card');add(card,'h3',f.name);add(card,'p',f.description);button(card,'방문·조건 문의',()=>ask(`${f.id} ${f.name}을 방문하여 ${f.service.join(', ')} 서비스의 조건·비용·시간·재료를 문의한다. 아직 결제·훈련 성공을 확정하지 않는다.`),busy());}button(body,tab==='shop'?'현지 상점 알아보기':'수련 기회·지도자 알아보기',()=>ask(tab==='shop'?'현재 장소의 실제 상점과 거래 가능 품목·가격·재고를 확인한다. 보유금과 소지품을 지킨다.':'현재 직업·경지·장착 기술에 맞는 실제 수련 장소와 지도자의 조건·비용·시간을 확인한다. 수련만으로 레벨·서클·깨달음 돌파를 자동 지급하지 않는다.'),busy());button(body,tab==='shop'?'장비·소지품 정비':'능력치·스킬 장착',()=>{close();switchTo(tab==='shop'?'inventory':'status');});}
  if(tab==='rest'){add(body,'h3','안전한 곳에서 휴식');add(body,'p',`HP ${state.player.hp??'—'}/${state.player.maxHp??'—'} · MP ${state.player.mp??'—'}/${state.player.maxMp??'—'} · 부상과 휴식 장소에 따라 회복이 달라집니다.`);button(body,'휴식 조건 확인',()=>ask('현재 장소에서 안전하게 쉴 수 있는 곳과 숙박·치료 비용 및 필요한 시간을 확인한다. 부상·피로·현재 HP/MP를 바탕으로 회복 가능한 범위를 설명하고 무조건 완전 회복하지 않는다.'),busy());}
  if(tab==='travel'){add(body,'p',`실제 출발지 ${location.region||'미확인'} · 지도 열람으로 위치는 바뀌지 않습니다.`);for(const d of options.dungeons){const card=add(body,'article','','adventure-card');add(card,'h3',d.name);add(card,'p',`권장 Lv.${d.level_range.join('–')} · ${d.danger_rank}`);const rewards=state.world_engine?.dungeons?.[d.id]?.claimed?'최초 보상 수령 완료 · 반복 보상은 재출현 확인 필요':'최초 보상은 실제 클리어 후 지급';add(card,'p',rewards);add(card,'p',dungeonRewardPreview(d,state));button(card,'경로·시간·보상 확인',()=>ask(`${d.id} ${d.name}으로 향하는 현지 경로·이동 시간·입구 조건·위험·승인된 보상과 재료를 확인한다. 첫 방문이나 보스는 생략하지 않고 아직 출정하지 않는다.`),busy());button(card,'탐험·출정 요청',()=>ask(`${d.id} ${d.name}으로 출정한다. 장비·HP/MP·진입 조건·국경·이동 시간·습격 위험을 실제 판정하고 도착 후에만 던전 사건을 확인한다.`),busy());}button(body,'안전한 주변 탐색 요청',()=>ask('현 위치 주변에서 현재 능력으로 접근 가능한 길과 장소를 탐색한다. 경로·시간·위험을 확인하고 실제 이동 결과를 기록한다.'),busy());button(body,'세계지도에서 목적지 확인',()=>{close();switchTo('map');});}
 }
 open.onclick=()=>{const menu=document.querySelector('.game-utility');if(menu)menu.open=false;panel.hidden=false;open.setAttribute('aria-expanded','true');tab='home';refresh();panel.querySelector('button')?.focus();};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const list=[...panel.querySelectorAll('button,summary')].filter(b=>!b.disabled);if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 return {render:refresh};
}
