// Generated public-only mirror of faction_locations.json.
export const factionLocations = [
  {
    "id": "KN01",
    "type": "knight_order",
    "name": "청금사자 근위기사단",
    "region": "west",
    "anchor_id": "CW",
    "x": 0.26822917,
    "y": 0.36621094,
    "leader": "로데릭 바란",
    "group": "벨로아 왕실",
    "detail": "왕궁 서문병영 · 중장기병"
  },
  {
    "id": "KN02",
    "type": "knight_order",
    "name": "적장미 선봉기사단",
    "region": "west",
    "anchor_id": "W4",
    "x": 0.34635417,
    "y": 0.54003906,
    "leader": "리네트 로젠펠트",
    "group": "벨로아",
    "detail": "장미채 성채 · 중앙전선 돌격"
  },
  {
    "id": "KN03",
    "type": "knight_order",
    "name": "청뢰성벽 기사단",
    "region": "east",
    "anchor_id": "CE",
    "x": 0.75,
    "y": 0.41210938,
    "leader": "카르스 에델",
    "group": "드라켄 왕실",
    "detail": "수정성 내부 · 룬 방벽"
  },
  {
    "id": "KN04",
    "type": "knight_order",
    "name": "흑정찰 균열기사단",
    "region": "east",
    "anchor_id": "E1",
    "x": 0.72135416,
    "y": 0.32324218,
    "leader": "베라 칼트하임",
    "group": "드라켄",
    "detail": "북동 감시초소 · 이상지대 경계"
  },
  {
    "id": "KN05",
    "type": "knight_order",
    "name": "백파도 친위기사단",
    "region": "south",
    "anchor_id": "CS",
    "x": 0.53320312,
    "y": 0.76171875,
    "leader": "알렉시아 바레트",
    "group": "루메린 왕실",
    "detail": "해양궁 · 여왕 경호"
  },
  {
    "id": "KN06",
    "type": "knight_order",
    "name": "해풍수호 기사단",
    "region": "south",
    "anchor_id": "S3",
    "x": 0.59114584,
    "y": 0.67285156,
    "leader": "루카 마리노",
    "group": "루메린",
    "detail": "해군기지 북부 부두 · 승선전"
  },
  {
    "id": "MT01",
    "type": "magic_tower",
    "name": "칠원기록탑",
    "region": "west",
    "anchor_id": "W2",
    "x": 0.33203125,
    "y": 0.35058594,
    "leader": "오르델 비안",
    "group": "마법탑",
    "detail": "역사 기록과 마나 측정"
  },
  {
    "id": "MT02",
    "type": "magic_tower",
    "name": "청동뇌명탑",
    "region": "east",
    "anchor_id": "E2",
    "x": 0.63671875,
    "y": 0.42871094,
    "leader": "이레나 솔브",
    "group": "마법탑",
    "detail": "7서클 탑주 · 전기 마도구"
  },
  {
    "id": "MT03",
    "type": "magic_tower",
    "name": "청류융합탑",
    "region": "south",
    "anchor_id": "S3",
    "x": 0.53776042,
    "y": 0.72363281,
    "leader": "마레나 에르노",
    "group": "마법탑",
    "detail": "물·바람 연구"
  },
  {
    "id": "MT04",
    "type": "magic_tower",
    "name": "황혼음영탑",
    "region": "south",
    "anchor_id": "S4",
    "x": 0.56315104,
    "y": 0.80566406,
    "leader": "세드릭 바일",
    "group": "마법탑",
    "detail": "빛·암흑 공존 연구"
  },
  {
    "id": "MT05",
    "type": "magic_tower",
    "name": "회색초석탑",
    "region": "east",
    "anchor_id": "E3",
    "x": 0.69401042,
    "y": 0.46875,
    "leader": "테레사 가른",
    "group": "마법탑",
    "detail": "방벽·마나광 안정"
  },
  {
    "id": "SHTH",
    "type": "sanctuary",
    "name": "영시의 대서고",
    "region": "west",
    "anchor_id": "W2",
    "x": 0.29557292,
    "y": 0.41308594,
    "leader": "율렌 크라스",
    "group": "테오르 · 영시기록원",
    "detail": "시간 성자"
  },
  {
    "id": "SHSP",
    "type": "sanctuary",
    "name": "열두 문 회랑",
    "region": "south",
    "anchor_id": "S2",
    "x": 0.45247395,
    "y": 0.60839843,
    "leader": "세아 메르",
    "group": "아스텔리온 · 천문의 길회",
    "detail": "공간 성녀"
  },
  {
    "id": "SHLI",
    "type": "sanctuary",
    "name": "첫새벽 요양원",
    "region": "west",
    "anchor_id": "W3",
    "x": 0.26692708,
    "y": 0.4609375,
    "leader": "로나 에일",
    "group": "엘리시아 · 새벽샘 성회",
    "detail": "생명 성녀"
  },
  {
    "id": "SHDE",
    "type": "sanctuary",
    "name": "은종의 묘역",
    "region": "west",
    "anchor_id": "W1",
    "x": 0.21158854,
    "y": 0.33496094,
    "leader": "다미엔 솔",
    "group": "모르베인 · 종언의 안식원",
    "detail": "죽음 성자"
  },
  {
    "id": "SHFI",
    "type": "sanctuary",
    "name": "불멸의 대화로",
    "region": "west",
    "anchor_id": "W4",
    "x": 0.29752605,
    "y": 0.57421875,
    "leader": "카르민 테라",
    "group": "이그나르 · 홍염의 화로단",
    "detail": "불 성녀"
  },
  {
    "id": "SHWA",
    "type": "sanctuary",
    "name": "푸른 만 성소",
    "region": "south",
    "anchor_id": "S1",
    "x": 0.34700521,
    "y": 0.71679688,
    "leader": "이오나 베르",
    "group": "네레이아 · 푸른 조수성당",
    "detail": "물 성녀"
  },
  {
    "id": "SHWI",
    "type": "sanctuary",
    "name": "바람등대 순례정",
    "region": "south",
    "anchor_id": "S3",
    "x": 0.60546875,
    "y": 0.68164063,
    "leader": "타빈 루오",
    "group": "실피레아 · 순풍의 순례단",
    "detail": "바람 성자"
  },
  {
    "id": "SHEL",
    "type": "sanctuary",
    "name": "천뢰실험성당",
    "region": "east",
    "anchor_id": "E2",
    "x": 0.68229167,
    "y": 0.44433594,
    "leader": "레이카스 룬",
    "group": "볼테리온 · 천뢰공학회",
    "detail": "전기 성자"
  },
  {
    "id": "SHLG",
    "type": "sanctuary",
    "name": "백일 대성당",
    "region": "west",
    "anchor_id": "W2",
    "x": 0.30989584,
    "y": 0.34179688,
    "leader": "에스텔 루나르",
    "group": "루미아 · 광휘대성당",
    "detail": "빛 성녀"
  },
  {
    "id": "SHDK",
    "type": "sanctuary",
    "name": "그늘의 안식집",
    "region": "east",
    "anchor_id": "E1",
    "x": 0.76171875,
    "y": 0.38378906,
    "leader": "니엘 마크",
    "group": "녹테라 · 흑월의 성소",
    "detail": "암흑 성자 · 보호 성소의 공개 입구"
  },
  {
    "id": "SHFA",
    "type": "sanctuary",
    "name": "삼실의 중재관",
    "region": "south",
    "anchor_id": "S4",
    "x": 0.50651041,
    "y": 0.828125,
    "leader": "베니아 사르",
    "group": "카이로스 · 인연의 직조회",
    "detail": "운명 성녀"
  },
  {
    "id": "GD01",
    "type": "guild",
    "name": "대륙길잡이 길드 본관",
    "region": "west",
    "anchor_id": "W5",
    "x": 0.41536458,
    "y": 0.640625,
    "leader": "아델라 베인",
    "group": "모험가 길드",
    "detail": "관문 공회관 · 의뢰 중개"
  },
  {
    "id": "GD02",
    "type": "guild",
    "name": "대륙길잡이 길드 교량 분회",
    "region": "east",
    "anchor_id": "E4",
    "x": 0.671875,
    "y": 0.58203125,
    "leader": null,
    "group": "모험가 길드",
    "detail": "실베른 협곡 다리"
  },
  {
    "id": "GD03",
    "type": "guild",
    "name": "대륙길잡이 길드 항구 분회",
    "region": "south",
    "anchor_id": "S1",
    "x": 0.36328125,
    "y": 0.77636719,
    "leader": null,
    "group": "모험가 길드",
    "detail": "항구 의뢰 사무소"
  },
  {
    "id": "MC01",
    "type": "mercenary",
    "name": "쇠갈퀴 용병단 야영지",
    "region": "west",
    "anchor_id": "W4",
    "x": 0.35546875,
    "y": 0.57910156,
    "leader": "바르토 크렘",
    "group": "용병단",
    "detail": "전선 이동 야영지 · 위치는 변동 가능"
  },
  {
    "id": "MC02",
    "type": "mercenary",
    "name": "백범선 해상호위조합",
    "region": "south",
    "anchor_id": "S3",
    "x": 0.60091146,
    "y": 0.7421875,
    "leader": "마일로 세인",
    "group": "해상호위",
    "detail": "호송선 부두"
  },
  {
    "id": "TR01",
    "type": "merchant",
    "name": "황금돛 상단연맹 본회",
    "region": "south",
    "anchor_id": "S1",
    "x": 0.39453125,
    "y": 0.72558594,
    "leader": "오르넬 파시스",
    "group": "상단",
    "detail": "남서 항만 상회"
  },
  {
    "id": "TR02",
    "type": "merchant",
    "name": "황금돛 상단연맹 금융 지점",
    "region": "south",
    "anchor_id": "S4",
    "x": 0.52604166,
    "y": 0.765625,
    "leader": null,
    "group": "상단",
    "detail": "상업·금융 업무"
  },
  {
    "id": "TR03",
    "type": "merchant",
    "name": "황금돛 상단연맹 벨로아 연락소",
    "region": "west",
    "anchor_id": "W5",
    "x": 0.38411458,
    "y": 0.65039063,
    "leader": null,
    "group": "상단",
    "detail": "관문 거래소"
  },
  {
    "id": "TR04",
    "type": "merchant",
    "name": "회색다리 대상단 본회",
    "region": "east",
    "anchor_id": "E4",
    "x": 0.71289063,
    "y": 0.53710937,
    "leader": "미르나 에셀",
    "group": "상단",
    "detail": "육상 교역 중개"
  },
  {
    "id": "TR05",
    "type": "merchant",
    "name": "회색다리 대상단 출장소",
    "region": "west",
    "anchor_id": "W5",
    "x": 0.36783854,
    "y": 0.60253906,
    "leader": null,
    "group": "상단",
    "detail": "국경 교역 창고"
  },
  {
    "id": "RS01",
    "type": "civic",
    "name": "새벽의 들불 공개 농민 모임",
    "region": "west",
    "anchor_id": "W3",
    "x": 0.22916666,
    "y": 0.50488281,
    "leader": "하나 미렛",
    "group": "농민 단체",
    "detail": "농촌 소작 개혁 모임"
  },
  {
    "id": "RS02",
    "type": "civic",
    "name": "청회 수정회 노동회관",
    "region": "east",
    "anchor_id": "E2",
    "x": 0.68489583,
    "y": 0.37792969,
    "leader": "도렌 페일",
    "group": "노동 단체",
    "detail": "공방·광산 노동자 회합"
  },
  {
    "id": "RS03",
    "type": "civic",
    "name": "흰물결 자치동맹 회관",
    "region": "south",
    "anchor_id": "S3",
    "x": 0.54166667,
    "y": 0.68066406,
    "leader": "이벨라 도스",
    "group": "항구 시민",
    "detail": "어업권·항만세 교섭"
  },
  {
    "id": "CV01",
    "type": "civic",
    "name": "전쟁유족 공동구호회 벨로아 출장소",
    "region": "west",
    "anchor_id": "W3",
    "x": 0.21289062,
    "y": 0.453125,
    "leader": "베르나 크리스",
    "group": "초국경 구호회",
    "detail": "부상자·유족 상담"
  },
  {
    "id": "CV02",
    "type": "diplomacy",
    "name": "세국 전쟁중재회 회합 여관",
    "region": "south",
    "anchor_id": "S2",
    "x": 0.50390625,
    "y": 0.6640625,
    "leader": "헤스틴 바우어",
    "group": "중재 조직",
    "detail": "포로 교환·부분 휴전"
  }
];
