// Public map facts generated from LORDSHIPS.md. Hidden ambitions, events and secrets are excluded.
export const lordships = {
  "W1": {
    "id": "W1",
    "name": "노르발트 변경백령",
    "kingdom": "벨로아",
    "lord": "에드릭 노르발트",
    "house": "노르발트",
    "crest": "검은 곰·은빛 산봉우리",
    "economy": "목재·모피·산양·빙설초",
    "terrain": "산악 나무 요새와 겨울 식량난",
    "population": 82000,
    "standingArmy": 1400,
    "knights": 130,
    "mages": 12
  },
  "W2": {
    "id": "W2",
    "name": "발렌하르트 공작령",
    "kingdom": "벨로아",
    "lord": "카시안 발렌하르트",
    "house": "발렌하르트",
    "crest": "은사자·푸른 방패",
    "economy": "제련·말 거래·고급 갑옷·징세 대행",
    "terrain": "왕도 주변 산업·기사학교와 관료 파벌",
    "population": 165000,
    "standingArmy": 2400,
    "knights": 410,
    "mages": 25
  },
  "W3": {
    "id": "W3",
    "name": "엘름베르크 백작령",
    "kingdom": "벨로아",
    "lord": "마르타 엘름베르크",
    "house": "엘름베르크",
    "crest": "세 이삭·갈색 들판",
    "economy": "밀·보리·치즈·종자",
    "terrain": "풍작이나 군량 징발과 소작료 갈등",
    "population": 146000,
    "standingArmy": 900,
    "knights": 90,
    "mages": 8
  },
  "W4": {
    "id": "W4",
    "name": "로젠펠트 후작령",
    "kingdom": "벨로아",
    "lord": "율리안 로젠펠트",
    "house": "로젠펠트",
    "crest": "적장미·교차 창",
    "economy": "군마·가죽·사료·창 제조",
    "terrain": "요새 연쇄와 난민 유입, 군량 소모",
    "population": 112000,
    "standingArmy": 3100,
    "knights": 320,
    "mages": 18
  },
  "W5": {
    "id": "W5",
    "name": "아르덴슈타인 백작령",
    "kingdom": "벨로아",
    "lord": "비올레트 아르덴슈타인",
    "house": "아르덴슈타인",
    "crest": "은매·붉은 다리",
    "economy": "포도주·양모·통행세·수레 제작",
    "terrain": "교역 교차로와 조세 장벽",
    "population": 98000,
    "standingArmy": 1150,
    "knights": 145,
    "mages": 11
  },
  "E1": {
    "id": "E1",
    "name": "칼트하임 변경백령",
    "kingdom": "드라켄",
    "lord": "하인리히 칼트하임",
    "house": "칼트하임",
    "crest": "검은 늑대·청색 첨봉",
    "economy": "광산 경비·냉철·희귀 광석 선별",
    "terrain": "산길 관문·오염 지역 접근 통제",
    "population": 64000,
    "standingArmy": 1750,
    "knights": 135,
    "mages": 16
  },
  "E2": {
    "id": "E2",
    "name": "아이젠크로네 공작령",
    "kingdom": "드라켄",
    "lord": "셀리아 아이젠크로네",
    "house": "아이젠크로네",
    "crest": "수정 왕관·톱니 원",
    "economy": "마도구·합금·수정 가공·기계",
    "terrain": "대공방과 마법탑·노동자 파업",
    "population": 152000,
    "standingArmy": 1800,
    "knights": 150,
    "mages": 44
  },
  "E3": {
    "id": "E3",
    "name": "베르크슈타인 후작령",
    "kingdom": "드라켄",
    "lord": "발터 베르크슈타인",
    "house": "베르크슈타인",
    "crest": "철산양·검은 성채",
    "economy": "마나광·철광·대포 부품·석재",
    "terrain": "협곡의 장대 요새, 채굴민 임금 분쟁",
    "population": 109000,
    "standingArmy": 2700,
    "knights": 260,
    "mages": 19
  },
  "E4": {
    "id": "E4",
    "name": "실베른 백작령",
    "kingdom": "드라켄",
    "lord": "에밀 실베른",
    "house": "실베른",
    "crest": "은교량·세 개의 별",
    "economy": "통행료·고원 약초·정밀공구",
    "terrain": "험로·협곡 다리·상단 통제",
    "population": 87000,
    "standingArmy": 850,
    "knights": 85,
    "mages": 14
  },
  "S1": {
    "id": "S1",
    "name": "벨마리나 후작령",
    "kingdom": "루메린",
    "lord": "도미니크 벨마리나",
    "house": "벨마리나",
    "crest": "금색 돛·푸른 파도",
    "economy": "향신료·조선·해외 무역·보험",
    "terrain": "거대 부두, 해적 침입과 계약 사기",
    "population": 137000,
    "standingArmy": 1250,
    "knights": 115,
    "mages": 12
  },
  "S2": {
    "id": "S2",
    "name": "세르반 공작령",
    "kingdom": "루메린",
    "lord": "이사벨 세르반",
    "house": "세르반",
    "crest": "백색 매·금빛 길",
    "economy": "마차·올리브·군량 계약·도로 관세",
    "terrain": "전략적 내륙 요새, 징집 반발",
    "population": 121000,
    "standingArmy": 2250,
    "knights": 270,
    "mages": 16
  },
  "S3": {
    "id": "S3",
    "name": "아쿠아렌 백작령",
    "kingdom": "루메린",
    "lord": "티에라 아쿠아렌",
    "house": "아쿠아렌",
    "crest": "은돌고래·쌍파도",
    "economy": "조선·소금·어획·선박 수리",
    "terrain": "조선소와 항해 학교, 숙련 선원 부족",
    "population": 118000,
    "standingArmy": 1500,
    "knights": 95,
    "mages": 13
  },
  "S4": {
    "id": "S4",
    "name": "솔메리아 백작령",
    "kingdom": "루메린",
    "lord": "라파엘 솔메리아",
    "house": "솔메리아",
    "crest": "금열쇠·태양 이삭",
    "economy": "금융·과수·비단·학술 후원",
    "terrain": "왕도 남쪽 상업·농경 혼합 지대, 고리대 문제",
    "population": 133000,
    "standingArmy": 950,
    "knights": 80,
    "mages": 10
  }
};
